# Generated by Django 5.1.2 on 2024-10-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterorder',
            name='creator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datacenterorder',
            name='moderator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
