# Generated by Django 5.1.1 on 2024-09-19 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacenterorderservice',
            old_name='is_main',
            new_name='main_status',
        ),
        migrations.RemoveField(
            model_name='datacenterorder',
            name='address',
        ),
        migrations.AddField(
            model_name='datacenterorder',
            name='formation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacenterorder',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datacenterorder',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datacenterorderservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
