# Generated by Django 5.1.1 on 2024-09-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0002_rename_is_main_datacenterorderservice_main_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
