# Generated by Django 5.1.2 on 2024-10-21 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0002_alter_datacenterorder_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterorder',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datacenterorder',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_moderated', to=settings.AUTH_USER_MODEL),
        ),
    ]
