# Generated by Django 5.1.1 on 2024-09-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0003_datacenterservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterservice',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
