# Generated by Django 5.1.1 on 2024-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0004_alter_datacenterservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='datacenterorder',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
