# Generated by Django 5.1.1 on 2024-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0005_datacenterorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
