# Generated by Django 5.1.1 on 2024-09-22 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0007_alter_datacenterorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterorder',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
