# Generated by Django 5.1.1 on 2024-09-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0008_alter_datacenterorder_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
