# Generated by Django 5.1.1 on 2024-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter_app', '0009_alter_datacenterorder_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacenterorderservice',
            name='main_status',
        ),
        migrations.AlterField(
            model_name='datacenterorder',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacenterorderservice',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datacenterservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacenterservice',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datacenterservice',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
